print("         ♥♥♥♥♥ LAS MATERIAS QUE MAS ME HAN COSTADO EN EL AÑO ♥♥♥♥♥         ")
print("#MATEMATICA")
print("#COMPUTACION")
print("#QUIMICA")
print("#BIOLOGIA")
print("----------------------------------------------------------------------------------------------------------------------------------------------------------")
print("MATEMATICA")
print("Me cuesta mucho ya que casi siempre no le entiendo, trato de poner mucha atencion pero las explicaciones son muy rapidas pero no comprendo muchas cosas,    por ejemplo,ahora mismo estoy estudiando a   diario por la prueba que tendre del ministerio y realmente no comprendo por que mi mente no logra retener todo lo que   estudio.")
print("----------------------------------------------------------------------------------------------------------------------------------------------------------")
print("COMPUTACION")
print("Me es muy dificil aprenderlo son muchos temas en muy poco tiempo tampoco es muy bueno ya que como recibo clases en linea realmente la definicion de camara    es mas al igual que el audio aveces se escucha y otras veces no.")
print("----------------------------------------------------------------------------------------------------------------------------------------------------------")
print("QUIMICA")
print("En quimica creo que no me va mal pero realmente me cuesta aprender muchas formulas y tantos distintos tipos de elementos es algo que realmente me cuesta mucho.")
print("------------------------------------------------------------------------------------------------------------------------------------------------")
print("BIOLOGIA")
print("Biologia me cuesta casi que por lo mismo de quimica ya que son demasiadas celulas tantos  tipos de datos asi como distintos tipos de investigadores   con nombres realmente dificil")